
function TranslateChinese(text) {
    if(Object.keys(language_Chinese).indexOf(text) != -1)
        return language_Chinese[text];
    return text;
}

let language_Chinese = {
    "USA": "美國",
    "Italy": "義大利",
    "Spain": "西班牙",
    "China": "中國",
    "Germany": "德國",
    "France": "法國",
    "Iran": "伊朗",
    "UK": "英國",
    "Switzerland": "瑞士",
    "Belgium": "比利時",
    "Netherlands": "荷蘭",
    "Turkey": "土耳其",
    "S. Korea": "南韓",
    "Austria": "澳大利亞",
    "Canada": "加拿大",
    "Portugal": "葡萄牙",
    "Israel":"以色列",
    "Brazil":"巴西",
    "Norway":"挪威",
    "Australia":"澳大利亞",
    "Sweden":"瑞典",
    "Czechia":"捷克",
    "Ireland":"愛爾蘭",
    "Malaysia":"馬來西亞",
    "Denmark":"丹麥",
    "Chile":"智利",
    "Romania":"羅馬尼亞",
    "Poland":"波蘭",
    "Luxembourg":"盧森堡",
    "Ecuador":"厄瓜多爾",
    "Japan":"日本",
    "Russia":"俄羅斯",
    "Pakistan":"巴基斯坦",
    "Philippines":"菲律賓",
    "Thailand":"泰國",
    "Saudi Arabia":"沙烏地阿拉伯",
    "Indonesia":"印度尼西亞",
    "Finland":"芬蘭",
    "South Africa":"南非",
    "India":"印度",
    "Greece":"希臘",
    "Mexico":"墨西哥",
    "Iceland":"冰島",
    "Panama":"巴拿馬",
    "Argentina":"阿根廷",
    "Peru":"秘魯",
    "Dominican Republic":"多明尼加共和國",
    "Singapore":"新加坡",
    "Colombia":"哥倫比亞",
    "Croatia":"克羅地亞",
    "Serbia":"塞爾維亞",
    "Slovenia":"斯洛文尼亞",
    "Estonia":"愛沙尼亞",
    "Diamond Princess":"鑽石公主號",
    "Qatar":"卡塔爾",
    "Hong Kong":"香港",
    "Egypt":"埃及",
    "New Zealand":"紐西蘭",
    "Iraq":"伊拉克",
    "UAE":"阿聯酋",
    "Algeria":"阿爾及利亞",
    "Morocco":"摩洛哥",
    "Ukraine":"烏克蘭",
    "Bahrain":"巴林",
    "Lithuania":"立陶宛",
    "Armenia":"亞美尼亞",
    "Hungary":"匈牙利",
    "Lebanon":"黎巴嫩",
    "Latvia":"拉脫維亞",
    "Andorra":"安道爾",
    "Bosnia and Herzegovina":"波斯尼亞和黑塞哥維那",
    "Tunisia":"突尼斯",
    "Bulgaria":"保加利亞",
    "Slovakia":"斯洛伐克",
    "Costa Rica":"哥斯達黎加",
    "Uruguay":"烏拉圭",
    "Kazakhstan":"哈薩克斯坦",
    "Taiwan":"台灣",
    "Moldova":"摩爾多瓦",
    "North Macedonia":"北馬其頓",
    "Azerbaijan":"阿塞拜疆",
    "Jordan":"約旦",
    "Kuwait":"科威特",
    "Burkina Faso":"布基納法索",
    "San Marino":"聖馬力諾",
    "Cyprus":"塞浦路斯",
    "Réunion":"留尼旺",
    "Albania":"阿爾巴尼亞",
    "Vietnam":"越南",
    "Oman":"阿曼",
    "Cuba":"古巴",
    "Afghanistan":"阿富汗",
    "Ivory Coast":"象牙海岸",
    "Faeroe Islands":"法羅群島",
    "Senegal":"塞內加爾",
    "Malta":"馬耳他",
    "Ghana":"加納",
    "Belarus":"白俄羅斯",
    "Uzbekistan":"烏茲別克斯坦",
    "Honduras":"洪都拉斯",
    "Channel Islands":"海峽群島",
    "Cameroon":"喀麥隆",
    "Venezuela":"委內瑞拉",
    "Nigeria":"奈及利亞",
    "Mauritius":"毛里求斯",
    "Brunei":"汶萊",
    "Sri Lanka":"斯里蘭卡",
    "Palestine":"巴勒斯坦",
    "Cambodia":"柬埔寨",
    "Guadeloupe":"瓜德羅普島",
    "Georgia":"佐治亞州",
    "Bolivia":"玻利維亞",
    "Kyrgyzstan":"吉爾吉斯斯坦",
    "Martinique":"馬提尼克島",
    "Montenegro":"黑山共和國",
    "Trinidad and Tobago":"特立尼達和多巴哥",
    "Mayotte":"馬約特島",
    "DRC":"剛果民主共和國",
    "Rwanda":"盧旺達",
    "Gibraltar":"直布羅陀",
    "Paraguay":"巴拉圭",
    "Liechtenstein":"列支敦士登",
    "Kenya":"肯尼亞",
    "Aruba":"阿魯巴島",
    "Monaco":"摩納哥",
    "Isle of Man":"馬恩島",
    "Bangladesh":"孟加拉國",
    "Madagascar":"馬達加斯加",
    "French Guiana":"法屬圭亞那",
    "Macao":"澳門",
    "Jamaica":"牙買加",
    "Guatemala":"瓜地馬拉",
    "French Polynesia":"法屬波利尼西亞",
    "Zambia":"贊比亞",
    "Barbados":"巴巴多斯",
    "Uganda":"烏干達",
    "Togo":"多哥",
    "El Salvador":"薩爾瓦多",
    "Niger":"尼日爾",
    "Bermuda":"百慕大",
    "Mali":"馬里",
    "Ethiopia":"埃塞俄比亞",
    "Guinea":"幾內亞",
    "Tanzania":"坦桑尼亞",
    "Congo":"剛果",
    "Djibouti":"吉布地",
    "Maldives":"馬爾代夫",
    "Saint Martin":"聖馬丁",
    "New Caledonia":"新喀裡多尼亞",
    "Haiti":"海地",
    "Eritrea":"厄立特里亞",
    "Myanmar":"緬甸",
    "Bahamas":"巴哈馬",
    "Mongolia":"蒙古",
    "Equatorial Guinea":"赤道幾內亞",
    "Dominica":"多米尼加",
    "Cayman Islands":"開曼群島",
    "Namibia":"納米比亞",
    "Curaçao":"庫拉索",
    "Syria":"敘利亞",
    "Greenland":"格陵蘭",
    "Saint Lucia":"聖盧西亞",
    "Grenada":"格林納達",
    "Eswatini":"埃斯瓦蒂尼",
    "Suriname":"蘇里南",
    "Seychelles":"塞舌爾",
    "Mozambique":"莫桑比克",
    "Libya":"利比亞",
    "Laos":"老撾",
    "Guyana":"圭亞那",
    "Guinea-Bissau":"幾內亞比紹",
    "Zimbabwe":"津巴布韋",
    "Saint Kitts and Nevis":"聖基茨和尼維斯",
    "Gabon":"加蓬",
    "Antigua and Barbuda":"安提瓜和巴布達",
    "Angola":"安哥拉",
    "Vatican City":"梵蒂岡城",
    "Sudan":"蘇丹",
    "St. Barth":"聖巴特",
    "Sint Maarten":"聖馬丁",
    "Mauritania":"毛里塔尼亞",
    "Cabo Verde":"佛得角",
    "Benin":"貝寧",
    "Turks and Caicos":"特克斯和凱科斯群島",
    "Nepal":"尼泊爾",
    "Montserrat":"蒙特塞拉特",
    "Fiji":"斐濟",
    "Chad":"乍得",
    "Nicaragua":"尼加拉瓜",
    "Gambia":"岡比亞",
    "Bhutan":"不丹",
    "Somalia":"索馬里",
    "Liberia":"利比里亞",
    "CAR":"中非共和國",
    "Botswana":"博茨瓦納",
    "Belize":"伯利茲",
    "MS Zaandam":"贊丹號",
    "British Virgin Islands":"英屬維爾京群島",
    "Anguilla":"安圭拉島",
    "Timor-Leste":"東帝汶",
    "St. Vincent Grenadines":"聖文森特格林納丁斯",
    "Papua New Guinea":"巴布亞新幾內亞",
};